name: bekal
description: MarketPlace BelanjaKalimantan

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shimmer:
  photo_view:
  cached_network_image:
  image_picker:
  logger:
  adobe_xd:
  flutter_bloc:
  google_fonts:
  flutter_svg:
  #  rounded_floating_app_bar:
  flutter_neumorphic:
  flip_card:
  fullscreen:
  hexcolor:
  retrofit:
  dio:
  json_serializable:
  equatable:
  time_machine:
  json_annotation:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  formz:
  injectable:
  get_it: #service locator
  flutter_spinkit:
  freezed_annotation:
  shared_preferences:
  flutter_secure_storage:
  simple_animations:
  pin_code_fields:
  lottie:
  curved_navigation_bar:
  sizer:
  money2:
  intl:
  flutter_staggered_grid_view:
  modal_bottom_sheet:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  build_runner:
  freezed:
  json_serializable:
  json_annotation:
  retrofit_generator:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/ecommerce_splash.json
   - assets/ecommerce_splash1.json
   - assets/livebg.svg
   - assets/logout_background_blue_spot_1.svg
   - assets/logokabelv2.png
   - assets/hectic_logo.png
   - assets/sepatu.jpg
   - assets/tas.jpg
   - assets/tasselempang.jpg
   - assets/1.jpeg
   - assets/2.jpg
   - assets/3.jpg
   - assets/4.jpeg
   - assets/5.jpeg
   - assets/6.jpeg
   - assets/7.jpg
   - assets/splash1.gif
   - assets/splash2.json
   - assets/images/propic_sample.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: ghotic
      fonts:
        - asset: fonts/gothic.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
