name: bekal
description: MarketPlace BelanjaKalimantan

publish_to: 'none' 

version: 1.0.5+6

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer:
  photo_view:
  cached_network_image: ^3.2.0
  rflutter_alert: 
  fluttertoast:
  logger:
  adobe_xd: ^2.0.1
  flutter_bloc:
  google_fonts:
  flutter_svg:
  image_picker: ^0.8.4+9
  flutter_neumorphic:
  flip_card:
  fullscreen:
  hexcolor:
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  json_serializable: ^6.1.4
  equatable:
  time_machine:
  json_annotation: ^4.4.0
  cupertino_icons:
  formz:
  injectable:
  get_it:
  flutter_spinkit:
  freezed_annotation:
  shared_preferences: ^2.0.13
  flutter_secure_storage:
  simple_animations:
  pin_code_fields:
  lottie:
  curved_navigation_bar: ^1.0.3
  sizer: ^2.0.15
  money2:
  intl:
  flutter_staggered_grid_view:
  modal_bottom_sheet:
  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.9
  path: ^1.8.0
  loading_overlay: ^0.3.0
  stomp_dart_client:
  flutter_local_notifications:
  firebase_messaging: ^11.2.10
  network_to_file_image: ^3.1.0
  permission_handler:
  floating_action_bubble: ^1.1.4
  flutter_cache_manager:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  build_runner:
  freezed:
  retrofit_generator: ^4.0.1
  moor_generator: ^4.5.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_logo.png"
flutter:

  uses-material-design: true
  assets:
   - assets/ecommerce_splash.json
   - assets/ecommerce_splash1.json
   - assets/livebg.svg
   - assets/logout_background_blue_spot_1.svg
   - assets/logokabelv2.png
   - assets/hectic_logo.png
   - assets/sepatu.jpg
   - assets/tas.jpg
   - assets/tasselempang.jpg
   - assets/1.jpeg
   - assets/2.jpg
   - assets/3.jpg
   - assets/4.jpeg
   - assets/newlogo.png
   - assets/5.jpeg
   - assets/6.jpeg
   - assets/7.jpg
   - assets/splash1.gif
   - assets/splash2.json
   - assets/images/propic_sample.jpg
   - assets/data/cart.json
   - assets/data/courier.json
   
  fonts:
    - family: ghotic
      fonts:
        - asset: fonts/gothic.ttf
